//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPPE2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emplacement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emplacement()
        {
            this.sejours = new HashSet<sejour>();
        }
    
        public int id_emp { get; set; }
        public string id_tarif { get; set; }
        public int capacite { get; set; }
        public bool terasse { get; set; }
    
        public virtual tarif tarif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sejour> sejours { get; set; }
    }
}
