//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPPE2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_sejour
    {
        public string lib_type_sej { get; set; }
        public double coef_reduc { get; set; }
        public int id_sejour { get; set; }
    
        public virtual sejour sejour { get; set; }
    }
}
